### PR TITLE
431-team-c-task-create-teacher-dashboard-implement-layout-banner-and-buttons

### PR DESCRIPTION
**Pull request by WhitneyMeulink**
- Added the basic structure of the teacher_dashboard feature
- Included Flutter boilerplate code and initial setup
- Added resources and links for getting started with Flutter
- Updated README.md with project and team information

### CODE REVIEW

**Comment by WhitneyMeulink** [comment]
Teachers_Dashboard Dart and Flutter

**Comment by StephenBuley** [comment]
Hey Whitney thanks for working on the dashboard! It looks like you created an entirely new flutter project in the root of the repository (Summer2024), which added a bunch of unnecessary files. We need to just be working in the Team-C/test_wizard folder, and you shouldn't need to create a whole new flutter app. Let me know if you have any issues porting anything over.

**Comment by StephenBuley** [comment]
Hey Whitney, this one still has some issues - looks like the flutter project is still in the root of the repository. Please see the other comments for the end result. Thanks for working on all of these.

**Comment by StephenBuley** [comment]
Ok team, I've made the changes requested above, edited a few other things to make use of reusable components, and added tests. Awesome job @WhitneyMeulink getting this started, really cool search filter mechanic going on, and its always easier to edit something that already exists than it is to come up with it from the start, so really well done. @J-Gilberg , @hellohouseplant , @eshin2 , @Lanaismail , @GhauriM , in the interest of not reviewing a bunch of code I just wrote, please review when you can. Getting this through quickly would help since it is the new base of our app.

**Review by J-Gilberg — APPROVED** [review]

**Review by eshin2 — APPROVED** [review]
reviewed and approved

**Pull request merged**
