### PR TITLE
444-team-c-task---user-authentication-and-authorization---login--implement-layout-banner-and-buttons 

### LINKED ISSUE #444: [Team C] [Task] - User Authentication and Authorization - Login -implement-layout-banner-and-buttons

### PR DESCRIPTION
**Pull request by WhitneyMeulink**
- A banner and header with TestWizard branding.
- An image of a wizard for visual appeal.
- A button to initiate the OAuth login process with Moodle.

Thank you for your review.
-Whitney Meulink
login_dart_flutter

### CODE REVIEW

**Review by StephenBuley — CHANGES_REQUESTED** [review]
Whitney, it still looks like you are making a completely new flutter app for each page you are creating. We need to be adding views and components to our existing app, located in `umgc/Summer2024/Team-C/test_wizard`

**Comment by WhitneyMeulink** [comment]
Moved to the correct folder.

**Comment by StephenBuley** [comment]
It looks like you've included a new flutter app in the folder `login_page` and `modify_test` which should not exist. `login_page.dart` and `modify_test.dart` should be views inside of `Team-C/test_wizard/lib/views` folder (maybe named `<page_name>_view.dart` for consistency, but either way is fine) and should not create a new `MaterialApp` - we want all of our screens to be from one App, which starts in `Team-C/test_wizard/lib/main.dart`. See Lana's branch `lana_auth` for how she did that, or you could follow what I did and add a button that goes from the home screen to that page in my branch starting with `402-team-c-task...`. Either way, we shouldn't be returning a new `MaterialApp`, should ideally return a `Scaffold`.

**Comment by StephenBuley** [comment]
Ok team, same thing as the other one, I've made the changes requested above, edited a few other things to make use of reusable components, and added tests. Awesome job again @WhitneyMeulink getting this started, really cool search filter mechanic going on, and its always easier to edit something that already exists than it is to come up with it from the start, so really well done. @J-Gilberg , @hellohouseplant , @eshin2 , @Lanaismail , @GhauriM , in the interest of not reviewing a bunch of code I just wrote, please review when you can. Once we've got this we can update the dashboard component.

**Review by hellohouseplant — DISMISSED** [review]
We need a "login as guest" button now.

**Comment by StephenBuley** [comment]
Ok @hellohouseplant, changes made!

**Review by J-Gilberg — APPROVED** [review]

**Review by eshin2 — APPROVED** [review]
approved

**Review by StephenBuley — APPROVED** [review]

**Pull request merged**
