### PR TITLE
254 team c task   plugin testing and deploy integration testing

### LINKED ISSUE #254: [Team C] [Task] - [Plugin Testing and Deploy] Integration Testing
Test the plugins in a staging environment to ensure seamless integration with Moodle.

- [x] #376
- [x] #377
- [x] #378

### PR DESCRIPTION
**Pull request by StephenBuley**
Hello everyone, this adds the integration test. As we continue to flesh out our app, we can add more of these. For now, this one tests:
- Login with moodle invalid username and password fails and throws error
- Login as Guest correctly pulls a saved assessment
- Teacher Dashboard looks correct
- Create Assessment Form works as expected when not logged into moodle
- Add Questions form works as expected when there is no API key
- Cancel and back buttons work as expected.

Overall this doesn't test the following situations as these things are harder to mock:
- Logging in with moodle
- Correct call to Perplexity
- Error when parsing the data that comes back from perplexity

However, these have all been tested extensively by me manually.

I have also added this to GitHub Actions to run after the test function. I will be testing that on this pull request as well, it should bring our "Checks" up from 2 checks to 3.

Let me know if you have any questions. Thanks for the review.

### CODE REVIEW

**Review by eshin2 — DISMISSED** [review]
working for me. approved.

**Comment by eshin2** [comment]
I think it has something to do with the routing to dashboard maybe?

**Review by Lanaismail — APPROVED** [review]
I checked out the branch and flutter test to confirm and everything looks good.

**Comment by eshin2** [comment]
hmmm do you have the perplexity api key set up? Did you get a response back?

**Review by eshin2 — APPROVED** [review]
fixed black screen with stephen

**Pull request merged**
