### PR TITLE
Init Team folder and Project

### PR DESCRIPTION
**Pull request by J-Gilberg**
# **What Changed**
- Added Folder for Team-C
- Created a Flutter Project template.

### CODE REVIEW

**Review by StephenBuley — APPROVED** [review]
Initialize project with flutter CLI, looks good to me

**Comment by daniel-umgc** [comment]
@J-Gilberg  and @StephenBuley, I think you need a 2nd reviewer if you want to merge into developer branch. 

Also, it is great seeing you already adding the project's template.

**Review by eshin2 — APPROVED** [review]
approved project setup

**Comment by WhitneyMeulink** [comment]
Looks good, thank you!

**Pull request merged**
