### PR TITLE
Edit assessment to data

### PR DESCRIPTION
**Pull request by hellohouseplant**
Allows the modify_test_view page to pull from data
Allows the view_test_view page to pull from data
Allows the modify_test_view page to save to data
removed several unneeded buttons on modify_test_view and edit_test_view pages

### CODE REVIEW

**Review by J-Gilberg — APPROVED** [review]
Approved. Lets get this to Edward for LLM testing.

**Comment by eshin2** [comment]
I'm having some trouble fixing the failed test. Have you had the chance to look at this? @hellohouseplant @J-Gilberg

**Comment by eshin2** [comment]
fixed the analyze. Still not sure how to fix the test. I'll keep looking for now.

**Review by eshin2 — APPROVED** [review]
great job guys. approved.

**Pull request merged**
