### PR TITLE
441-team-c-feature-view-test---implement-layout-banner-and-buttons 

### LINKED ISSUE #441: [Team C] [Feature] View Test - Implement Layout banner and buttons

### PR DESCRIPTION
**Pull request by WhitneyMeulink**
- **Layout and Styling:**
  - Added a banner and header section with styling.
  - Created a table to display quiz versions, student names, and statuses.
  - Implemented a search filter input.
  - Added action buttons (Assign, Cancel, Save) with styling.

Thank you for your review.
-Whitney Meulink
view_tests

### CODE REVIEW

**Comment by WhitneyMeulink** [comment]
I moved it to the correct folder and added a column for results.
view_tests2

**Comment by StephenBuley** [comment]
It looks like you've included a new flutter app in the folder `view_test` which should not exist. `view_test.dart` should be a view inside of `Team-C/test_wizard/lib/views` folder (maybe named `view_test_view.dart` for consistency, but either way is fine) and should not create a new `MaterialApp` - we want all of our screens to be from one App, which starts in `Team-C/test_wizard/lib/main.dart`. See Lana's branch `lana_auth` for how she did that, or you could follow what I did and add a button that goes from the home screen to that page in my branch starting with `402-team-c-task...`. Either way, we shouldn't be returning a new `MaterialApp`, should ideally return a `Scaffold`.

**Comment by GhauriM** [comment]
Ok, I went ahead and made the changes Stephen requested. I also split the View_test file into the widget/viewtest.dart $ views/view_test_view.dart file to be consistent with the other features. Also, I removed the code that would create a whole new application. I ran the code and used the existing elevated button to launch the view_test page, but I did not push the changes in the main file for others to test. You can test the view_test page by changing the const line under MaterialPageRoute to const CreateViewTest().

**Review by StephenBuley — APPROVED** [review]
Looks good, made a couple of small tweaks, but overall left what you did. Not sure how you "re-committed" all of my past commits, but it shouldnt be too big of a deal. Thanks Mohammed

**Review by eshin2 — APPROVED** [review]
approved

**Pull request merged**
