### PR TITLE
437-team-c-task-edit-and-delete-tests---implement-layout-banner-and-buttons 

### LINKED ISSUE #437: [Team C] [Task] Edit and delete tests - Implement Layout banner and buttons

### PR DESCRIPTION
**Pull request by WhitneyMeulink**
- Added layout for the Test Modification page.
- Included features for editing and deleting tests.
- Implemented a banner and buttons for better navigation.
- Updated styles to match the design guidelines.
- Ensured responsiveness for various screen sizes.
- Whitney Meulink
modify_test

### CODE REVIEW

**Comment by StephenBuley** [comment]
Same thing here, I think this is in a separate folder outside of TeamC/test_wizard. Needs to all be contained. Let me know if you have issues porting anything over.

**Comment by WhitneyMeulink** [comment]
I moved it to the correct folder.

**Comment by StephenBuley** [comment]
Nice, looking a lot better! We should still remove the `modify_test` folder in the original repo. Also, if you could add some tests, that would be great, or if you would like me to as the QA Engineer, I'd be happy to do so as a separate PR or to pull this down before it gets merged.

**Comment by WhitneyMeulink** [comment]
I deleted the modify_test folder. Maybe it was after this push. Yes, could you do the test.

**Comment by StephenBuley** [comment]
It looks like you've included a new flutter app in the folder `modify_test` which should not exist. `modify_test.dart` should be a view inside of `Team-C/test_wizard/lib/views` folder (maybe named `modify_test_view.dart` for consistency, but either way is fine) and should not create a new `MaterialApp` - we want all of our screens to be from one App, which starts in `Team-C/test_wizard/lib/main.dart`. See Lana's branch `lana_auth` for how she did that, or you could follow what I did and add a button that goes from the home screen to that page in my branch starting with `402-team-c-task...`. Either way, we shouldn't be returning a new `MaterialApp`, should ideally return a `Scaffold`.

**Review by hellohouseplant — APPROVED** [review]
These changes make sense to me.

**Review by J-Gilberg — APPROVED** [review]

**Pull request merged**
